### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by troyane**
- Avoid usage of moved variable.
- Add `const` directives to (almost) all setters.
- Use `qFuzzyCompare` instead of `==` for `qreal`s.
- Use `qreal`s instead of `double`.
- Improve formatting in C++ part and in QML.

### CODE REVIEW

**Comment by aklevy** [comment]
Thanks !! The code looks much cleaner ! I tested and everything was fine. Now it's up to @jcelerier to test and do the merge.

**Comment by troyane** [comment]
@avilleret great, thanks. In addition to my changes I also recommend to edit all qml files inside `CreativeControls` to fit some coding conventions, e.g. http://doc.qt.io/qt-5/qml-codingconventions.html

**Comment by jcelerier** [comment]
thanks, everything looked fine ! did you use a script or something like this for reformatting the code ?

**Comment by troyane** [comment]
@jcelerier Unfortunately no. I was going to get familiar to code, so read it and make changes by the way.
**But** there are beautifiers for C++: http://doc.qt.io/qtcreator/creator-beautifier.html (it's great option, but still needs some human attention)
Unfortunately I can't find anything similar for QML.

**Comment by jcelerier** [comment]
yep, I use clang-format in other projects, I will add a .clang-format file here

**Comment by avilleret** [comment]
> @avilleret great, thanks. In addition to my changes I also recommend to edit all qml files inside `CreativeControls` to fit some coding conventions, e.g. http://doc.qt.io/qt-5/qml-codingconventions.html

I think I was wrongly mentioned in this comment, thanks go to @aklevy I guess :-)

**Comment by troyane** [comment]
@avilleret exactly. Sorry for bothering.

**Pull request merged**
